package uk.gov.justice.digital.hmpps.hmppsdocumentmanagementapi.resource

const val ROLE_DOCUMENT_READER = "ROLE_DOCUMENT_READER"
const val ROLE_DOCUMENT_WRITER = "ROLE_DOCUMENT_WRITER"
const val ROLE_DOCUMENT_ADMIN = "ROLE_DOCUMENT_ADMIN"

const val ROLE_DOCUMENT_TYPE_SAR = "ROLE_DOCUMENT_TYPE_SAR"
const val ROLE_DOCUMENT_TYPE_DISTINGUISHING_MARK_IMAGE = "ROLE_DOCUMENT_MANAGEMENT_API__DOCUMENT_TYPE_DISTINGUISHING_MARK_IMAGE__RW"
