#
# The "-local" profile is for running the API service locally against pre-existing
# docker containers that are listening on known port numbers for hmpps-auth (8090) and
# a postgres database (5432).
#

# Most values are inherited from - application.yml - except the following:

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          public-key-location: classpath:local-public-key.pub

  jpa:
    show-sql: true

# Container-provider local auth server
hmpps:
  auth:
    url: http://localhost:8090/auth

hmpps.s3:
  provider: localstack
  localstackUrl: http://localhost:4567
  buckets:
    document-management:
      bucketName: document-management
    prisoner-images:
      bucketName: prisoner-images

hmpps.sqs:
  provider: localstack
  localstackUrl: http://localhost:4567
  queues:
    audit:
      queueName: hmpps-audit
  topics:
    domainevents:
      arn: arn:aws:sns:eu-west-2:000000000000:hmpps-domain-events
