{{- if .Values.s3Sync.enabled }}
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: hmpps-document-management-api-s3-sync-cronjob
spec:
  schedule: "{{ .Values.s3Sync.schedule }}"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 5
  failedJobsHistoryLimit: 5
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: "{{ .Values.s3Sync.serviceAccountName }}"
          restartPolicy: OnFailure
          containers:
            - name: "{{ .Values.s3Sync.container.name }}"
              image: "{{ .Values.s3Sync.container.image }}"
              stdin: true
              tty: true
              securityContext:
                 allowPrivilegeEscalation: false
                 runAsNonRoot: true
                 runAsUser: 2000
              command: [ "/bin/sh", "-c" ]
              args:
                - >
                  aws s3 sync s3://$S3_SOURCE_BUCKET s3://$S3_DESTINATION_BUCKET --source-region $S3_SOURCE_REGION --region $S3_DESTINATION_REGION
              env:
                - name: S3_SOURCE_BUCKET
                  value: "{{ .Values.s3Sync.sourceBucket }}"
                - name: S3_DESTINATION_BUCKET
                  valueFrom:
                    secretKeyRef:
                      name: s3-output
                      key: "{{ index (index (index (index .Values "generic-service") "namespace_secrets") "s3-output") "S3_DOCUMENT_BUCKET_NAME" }}"
                - name: S3_SOURCE_REGION
                  value: "{{ index (index (index .Values "generic-service") "env") "AWS_REGION" }}"
                - name: S3_DESTINATION_REGION
                  value: "{{ index (index (index .Values "generic-service") "env") "AWS_REGION" }}"
{{- end }}
