---
# Per environment values which override defaults in hmpps-document-management-api/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: document-api-dev.hmpps.service.justice.gov.uk

  env:
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.dev.json
    HMPPS_AUTH_URL: https://sign-in-dev.hmpps.service.justice.gov.uk/auth


  allowlist:
    penetration-test-ip-1: 54.37.241.156/30
    penetration-test-ip-2: 167.71.136.237/32
    groups:
      - internal
      - circleci

# CloudPlatform AlertManager receiver to route prometheus alerts to slack
# See https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-alarms.html#creating-your-own-custom-alerts
generic-prometheus-alerts:
  alertSeverity: hmpps_document_management_api_non_prod

s3Sync:
  enabled: true
  schedule: 0 0 * * 1
  serviceAccountName: hmpps-document-management-dev-cross-srv-tst
  sourceBucket: cloud-platform-9f7916cd9d39324d81c052834a583ff8
  container:
    name: cross-service-s3-sync-dev-tst
    image: 754256621582.dkr.ecr.eu-west-2.amazonaws.com/webops/cloud-platform-service-pod:f9619b99ffe9ae511dde5e7e6e5b67ea289bbab5
